### ISSUE TITLE
可能是菜单显示错误

### ISSUE THREAD

**Issue by JiangQiYan713** [SlimefunGuguProject/ColoredEnderChests#1]
## Description (Required)
```
[19:29:57] [Server thread/INFO]: [ColoredEnderChests] Enabling ColoredEnderChests vBuild 1 zh-CN(ybw0014) (git b2c82c2)
[19:29:57] [Server thread/ERROR]: Error occurred while enabling ColoredEnderChests vBuild 1 zh-CN(ybw0014) (git b2c82c2) (Is it up to date?)
java.lang.NoSuchMethodError: 'void me.mrCookieSlime.Slimefun.api.inventory.BlockMenuPreset.<init>(java.lang.String, java.lang.String, boolean)'
	at io.github.thebusybiscuit.coloredenderchests.ColoredEnderChest$1.<init>(ColoredEnderChest.java:48) ~[ColoredEnderChests-Build 1 zh-CN(ybw0014) (git b2c82c2).jar:?]
	at io.github.thebusybiscuit.coloredenderchests.ColoredEnderChest.<init>(ColoredEnderChest.java:48) ~[ColoredEnderChests-Build 1 zh-CN(ybw0014) (git b2c82c2).jar:?]
	at io.github.thebusybiscuit.coloredenderchests.ColoredEnderChests.registerEnderChest(ColoredEnderChests.java:74) ~[ColoredEnderChests-Build 1 zh-CN(ybw0014) (git b2c82c2).jar:?]
	at io.github.thebusybiscuit.coloredenderchests.ColoredEnderChests.onEnable(ColoredEnderChests.java:65) ~[ColoredEnderChests-Build 1 zh-CN(ybw0014) (git b2c82c2).jar:?]
	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:281) ~[paper-api-1.19.4-R0.1-SNAPSHOT.jar:?]
	at io.papermc.paper.plugin.manager.PaperPluginInstanceManager.enablePlugin(PaperPluginInstanceManager.java:189) ~[paper-1.19.4.jar:git-Paper-547]
	at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.enablePlugin(PaperPluginManagerImpl.java:104) ~[paper-1.19.4.jar:git-Paper-547]
	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:507) ~[paper-api-1.19.4-R0.1-SNAPSHOT.jar:?]
	at org.bukkit.craftbukkit.v1_19_R3.CraftServer.enablePlugin(CraftServer.java:563) ~[paper-1.19.4.jar:git-Paper-547]
	at org.bukkit.craftbukkit.v1_19_R3.CraftServer.enablePlugins(CraftServer.java:474) ~[paper-1.19.4.jar:git-Paper-547]
	at net.minecraft.server.MinecraftServer.loadWorld0(MinecraftServer.java:638) ~[paper-1.19.4.jar:git-Paper-547]
	at net.minecraft.server.MinecraftServer.loadLevel(MinecraftServer.java:437) ~[paper-1.19.4.jar:git-Paper-547]
	at net.minecraft.server.dedicated.DedicatedServer.initServer(DedicatedServer.java:308) ~[paper-1.19.4.jar:git-Paper-547]
	at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1104) ~[paper-1.19.4.jar:git-Paper-547]
	at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:320) ~[paper-1.19.4.jar:git-Paper-547]
	at java.lang.Thread.run(Thread.java:833) ~[?:?]
[19:29:57] [Server thread/INFO]: [ColoredEnderChests] Disabling ColoredEnderChests vBuild 1 zh-CN(ybw0014) (git b2c82c2)
```

## Environment (Required)
Server Software: Paper
  Build: git-Paper-547 (MC: 1.19.4)
  Minecraft v1.19.4-R0.1-SNAPSHOT

 - Minecraft Version:
 - Slimefun Version:2023.06
  + GuizhanLibPlugin Build 22 (git 2f447db)
  + InfinityExpansion Build 5 zh-CN(SlimefunGuguProject) (git 018bfe1)
  + CMILib 1.2.4.5
  + TranscEndence Build 6 zh-CN(baoad) (git 12c5713)
  + Networks Build 76 zh-CN(ybw0014) (git bc8511f)
  + Residence 5.1.1.3
  + ExoticGarden Build 14 zh-CN(ybw0014) (git 0f8c287)
  + FluffyMachines Build 17 zh-CN(baoad) (git 1982d30)
  - ColoredEnderChests Build 1 zh-CN(ybw0014) (git b2c82c2)
  + SlimeTinker Build 43 zh-CN(ybw0014) (git 3bf69bc)
  + MobCapturer Build 9 zh-CN(ybw0014) (git 5cffcc5)
  + VillagerUtil Build 2 zh-CN(ybw0014) (git f019674)
  + FoxyMachines Build 18 zh-CN(ybw0014) (git d0ced94)
  + ExtraTools Build 5 zh-CN(SlimefunGuguProject) (git 7d520b7)
  + DyedBackpacks Build 2 zh-CN(baoad) (git 3a17d71)
  + SlimeGlue Build 20 (git 0543427)
  + SlimeCustomizer Build 19 zh-CN(SlimefunGuguProject) (git b240837)
  + SlimeHUD Build 8 zh-CN(SlimefunGuguProject) (git df37b14)
  + SimpleUtils Build 1 zh-CN(baoad) (git 721f4c9)
  + SfChunkInfo Build 8 zh-CN(ybw0014) (git 4ade4ca)
  + SlimefunAdvancements Build 11 zh-CN(ybw0014) (git 446b8ba)

**Comment by ybw0014** [comment]
已在新版本适配
